### ISSUE TITLE
👍 chores: setup project

### ISSUE THREAD

**Issue by nyomansunima** [nyomansunima/loona#1]
# About
Setup the project and the project repository

## Tasks

- [x] Add Readme
- [x] Add Contributing
- [x] Add License
- [x] Add Code of Conduct
- [x] Add Changelog
- [x] Add Wiki
- [x] Add pull request and Issue Template
- [x] Refactor the labels and Milestones
- [x] Add security
- [x] Add dependable bot
- [x] Create Project Using monorepos
- [x] Add Discussion
- [x] Add Funding
- [x] Add code scanning
- [x] Add deployment

**Comment by nyomansunima** [comment]
So let's start it

**Comment by nyomansunima** [comment]
It's done
