### ISSUE TITLE
🧐 chores: identify the project

### ISSUE THREAD

**Issue by nyomansunima** [nyomansunima/loona#3]
# About
Identify the problem, or idea and then create solutions of this project

## Task

- [ ] Identify the problem that solved using this project
- [ ] What kind of problem can solved with this app
- [ ] Why this app can solve the problem
